### ISSUE TITLE
When page element is defined, new line between ending bracket and starting new round bracket breaks syntax highlighting

### ISSUE THREAD

**Issue by profesor-test-dragan** [alchemycloud/sifu-atom-plugin#2]
Take a look at usersPage, I have hit enter after settings ending bracket to move elements starting round bracket to new line, and it breaks syntax highlighting.

Here is spec:
[tester.sifu.txt](https://github.com/drytools/sifu-atom-plugin/files/487136/tester.sifu.txt)

**Comment by vesin** [comment]
I tried to fix it but its realy complicated. Can we leave this for later...
PS: Im not sure is this good idea to support it, we can't break all language rules...

**Comment by profesor-test-dragan** [comment]
Deferred and closed, we decided to not support this.
