### ISSUE TITLE
Problem in validation with multiple sifu files in same folder

### ISSUE THREAD

**Issue by profesor-test-dragan** [alchemycloud/sifu-atom-plugin#3]
Open one sifu spec using Atom, make it with some validation error, copy content, create new document from Atom, paste content, save - error is reported only in one file, without showing tip where error originated from.
After investigating, I have found out our validation is validating only one sifu file in folder, and ignores rest, but we can define which file to validate using "-f" switch. 
Maybe we should pass full  path to the file which is being validated from Atom?

**Comment by vesin** [comment]
To check this, you will need to update plugin.
