### ISSUE TITLE
Fix several highlighting issues

### ISSUE THREAD

**Issue by profesor-test-dragan** [alchemycloud/sifu-atom-plugin#6]
The first is for home page by security role, highlighting shows entry in red, example:
home (signInPage, todosPage (ADMIN, MEMBER))

The second is developer name with dot or hyphen, example:
developer (profesor, i.vasiliu, vanja-test)

The third is for replaced 'with' and 'on' in find or paged endpoint inline query join, example:
        getFavourites paged[from DeviceFavourite
        join Content on DeviceFavourite.content
        join ContentLocalization with Content on ContentLocalization.content
        where DeviceFavourite.isDeleted == false
        and Content.isDeleted == false
        and ContentLocalization.isDeleted == false
        response(DeviceFavourite.id, Content.category, ContentLocalization.name),
        rest /device/favourites/all]

**Comment by vesin** [comment]
Please use atom in develop mode so you can check this without me building official version.
hint: use apm link

**Comment by profesor-test-dragan** [comment]
Ok, I did it like this:
First, run **apm develop <package-name>** to download package in develop mode, 
then run **atom -d .** from any directory.

and it works fine.
